
module.exports = {
	// public import
	jquery : 'libs/jquery-1.11.3.min.js',
	vuejs : 'libs/vue.min.js',
	tracker : 'libs/tracker.js',
	trackerConfig : 'commons/models/trackerConfig.js',
	// raphael: 'libs/raphael.min.js',
	// beenjs: 'libs/been.js',
	// raphaelTransform: 'libs/raphael-transform.js',
	jcrop: 'libs/jquery.Jcrop.min.js',
	slider: 'libs/bootstrap-slider.min.js',
	UtilWindow: 'commons/utils/UtilWindow.js',
	UtilMath: 'commons/utils/UtilMath.js',
	UtilCrop: 'commons/utils/UtilCrop.js',
	UtilParam: 'commons/utils/UtilParam.js',
	UtilXML: 'commons/utils/UtilXML.js',
	UtilProject: 'commons/utils/UtilProject.js',
	UtilDateFormat: 'commons/utils/UtilDateFormat.js',
	Prj: 'commons/models/Prj.js',
	Domains: 'commons/models/Domains.js',
	ImageListManage: 'commons/cmds/model/ImageListManage.js',
	ProjectManage:'commons/cmds/model/ProjectManage.js',
	ParamsManage: 'commons/cmds/model/ParamsManage.js',
	DrawManage: 'commons/cmds/model/DrawManage.js',
	ScaleManage: 'commons/cmds/model/ScaleManage.js',
	SpecManage: 'commons/cmds/model/SpecManage.js',
	JsonProjectManage:'commons/cmds/model/JsonProjectManage.js',
	EnvService:'commons/cmds/service/EnvService.js',
	ProjectService:'commons/cmds/service/ProjectService.js',
	UploadService: 'commons/cmds/service/UploadService.js',
	UserService:'commons/cmds/service/UserService.js',
	SpecService:'commons/cmds/service/SpecService.js',
	trackerService: 'commons/cmds/service/trackerService.js',
	ScreenshotController: 'app/Tshirt/cmds/ScreenshotController.js',
	// font-awesome: 'static/css/font-awesome.min.css',
	// bootstrap: 'static/css/bootstrap.min.css',
	// bootstrap-slider: 'static/css/bootstrap-slider.min.css',
	// beencss: 'static/css/been.css',
	// jcropcss: 'static/css/jquery.Jcrop.min.css',

	// // private import
	Store: 'app/Tshirt/models/Store.js',
	Spec: 'app/Tshirt/models/Spec.js',
	SpecController: 'app/Tshirt/cmds/SpecController.js',
	WarnController: 'app/Tshirt/cmds/WarnController.js',
	ProjectController: 'app/Tshirt/cmds/ProjectController.js',
	CanvasController: 'app/Tshirt/cmds/CanvasController.js',
	ImageController: 'app/Tshirt/cmds/ImageController.js',
	TextController: 'app/Tshirt/cmds/TextController.js',
	CompDispatch: 'app/Tshirt/components/CompDispatch.js',
	CompResize: 'app/Tshirt/components/CompResize.js',
	CompCanvas: 'app/Tshirt/components/CompCanvas.js',
	CompElementEvent: 'app/Tshirt/components/CompElementEvent.js'
};
