
module.exports = {
	// public import
	jquery : 'libs/jquery-1.11.3.min.js',
	vuejs : 'libs/vue.min.js',
	tracker : 'libs/tracker.js',
	trackerConfig : 'commons/models/trackerConfig.js',
	// raphael: 'libs/raphael.min.js',
	// beenjs: 'libs/been.js',
	// raphaelTransform: 'libs/raphael-transform.js',
	jcrop: 'libs/jquery.Jcrop.min.js',
	slider: 'libs/bootstrap-slider.min.js',
	colorpicker: 'libs/bootstrap-colorpicker.js',
	spectrum: 'libs/spectrum.js',
	Scale : 'libs/scale.js',
	UtilWindow: 'commons/utils/UtilWindow.js',
	UtilMath: 'commons/utils/UtilMath.js',
	UtilCrop: 'commons/utils/UtilCrop.js',
	UtilParam: 'commons/utils/UtilParam.js',
	UtilXML: 'commons/utils/UtilXML.js',
	UtilProject: 'commons/utils/UtilProject.js',
	UtilJSON: 'commons/utils/UtilJSON.js',
	UtilDateFormat: 'commons/utils/UtilDateFormat.js',
	UtilImage: 'commons/utils/UtilImage.js',
	Prj: 'commons/models/Prj.js',
	Domains: 'commons/models/Domains.js',
	ImageListManage: 'commons/cmds/model/ImageListManage.js',
	ProjectManage:'commons/cmds/model/ProjectManage.js',
	ParamsManage: 'commons/cmds/model/ParamsManage.js',
	DrawManage: 'commons/cmds/model/DrawManage.js',
	ScaleManage: 'commons/cmds/model/ScaleManage.js',
	SpecManage: 'commons/cmds/model/SpecManage.js',
	JsonProjectManage:'commons/cmds/model/JsonProjectManage.js',
	EnvService:'commons/cmds/service/EnvService.js',
	ProjectService:'commons/cmds/service/ProjectService.js',
	UploadService: 'commons/cmds/service/UploadService.js',
	UserService:'commons/cmds/service/UserService.js',
	SpecService:'commons/cmds/service/SpecService.js',
	ImageService:'commons/cmds/service/ImageService.js',
	trackerService: 'commons/cmds/service/trackerService.js',
	JsonProjectService: 'commons/cmds/service/JsonProjectService.js',
	ScreenshotController: 'app/LittleModernCanvas/cmds/ScreenshotController.js',
	UploadController: 'app/LittleModernCanvas/cmds/UploadController.js',
	TemplateService: 'commons/cmds/service/TemplateService.js',
	OptionConfig: 'commons/models/OptionConfig.js',
	// font-awesome: 'static/css/font-awesome.min.css',
	// bootstrap: 'static/css/bootstrap.min.css',
	// bootstrap-slider: 'static/css/bootstrap-slider.min.css',
	// beencss: 'static/css/been.css',
	// jcropcss: 'static/css/jquery.Jcrop.min.css',

	// // private import
	Store: 'app/LittleModernCanvas/models/Store.js',
	Spec: 'app/LittleModernCanvas/models/Spec.js',
	SpecController: 'app/LittleModernCanvas/cmds/SpecController.js',
	WarnController: 'app/LittleModernCanvas/cmds/WarnController.js',
	ProjectController: 'app/LittleModernCanvas/cmds/ProjectController.js',
	CanvasController: 'app/LittleModernCanvas/cmds/CanvasController.js',
	ImageController: 'app/LittleModernCanvas/cmds/ImageController.js',
	TextController: 'app/LittleModernCanvas/cmds/TextController.js',
	CompDispatch: 'app/LittleModernCanvas/components/CompDispatch.js',
	CompResize: 'app/LittleModernCanvas/components/CompResize.js',
	CompCanvas: 'app/LittleModernCanvas/components/CompCanvas.js',
	CompElementEvent: 'app/LittleModernCanvas/components/CompElementEvent.js',
	UpgradeProjectController: 'app/LittleModernCanvas/cmds/UpgradeProjectController'
};
