module.exports = {
	// public import
	jquery : 'libs/jquery-1.11.3.min.js',
	vuejs : 'libs/vue.min.js',
	html2canvas : 'libs/html2canvas.js',
	jcrop: 'libs/jquery.Jcrop.min.js',
	slider: 'libs/bootstrap-slider.min.js',
	colorpicker: 'libs/bootstrap-colorpicker.js',
	spectrum: 'libs/spectrum.js',
	Scale : 'libs/scale.js',
	UtilWindow: 'commons/utils/UtilWindow.js',
	UtilMath: 'commons/utils/UtilMath.js',
	UtilCrop: 'commons/utils/UtilCrop.js',
	UtilParam: 'commons/utils/UtilParam.js',
	UtilXML: 'commons/utils/UtilXML.js',
	UtilProject: 'commons/utils/UtilProject.js',
	Prj: 'commons/models/Prj.js',
	Domains: 'commons/models/Domains.js',
	ImageListManage: 'commons/cmds/model/ImageListManage.js',
	ProjectManage:'commons/cmds/model/ProjectManage.js',
	ParamsManage: 'commons/cmds/model/ParamsManage.js',
	DrawManage: 'commons/cmds/model/DrawManage.js',
	ScaleManage: 'commons/cmds/model/ScaleManage.js',
	SpecManage: 'commons/cmds/model/SpecManage.js',
	EnvService:'commons/cmds/service/EnvService.js',
	ProjectService:'commons/cmds/service/ProjectService.js',
	UploadService: 'commons/cmds/service/UploadService.js',
	UserService:'commons/cmds/service/UserService.js',
	SpecService:'commons/cmds/service/SpecService.js',
	ImageService:'commons/cmds/service/ImageService.js',
	ScreenshotController: 'app/WallArts/cmds/ScreenshotController.js',
	UploadController: 'app/WallArts/cmds/UploadController.js',
	TemplateService: 'commons/cmds/service/TemplateService.js',
	OptionConfig: 'commons/models/OptionConfig.js',
	CompProductAttribute: 'commons/components/CompProductAttribute',


	// // private import
	Store: 'app/WallArts/models/Store.js',
	Spec: 'app/WallArts/models/Spec.js',
	SpecController: 'app/WallArts/cmds/SpecController.js',
	WarnController: 'app/WallArts/cmds/WarnController.js',
	ProjectController: 'app/WallArts/cmds/ProjectController.js',
	CanvasController: 'app/WallArts/cmds/CanvasController.js',
	ImageController: 'app/WallArts/cmds/ImageController.js',
	TextController: 'app/WallArts/cmds/TextController.js',
	CompDispatch: 'app/WallArts/components/CompDispatch.js',
	CompResize: 'app/WallArts/components/CompResize.js',
	CompCanvas: 'app/WallArts/components/CompCanvas.js',
	CompElementEvent: 'app/WallArts/components/CompElementEvent.js'
};
